services:
  # Bronze Layer: MySQL
  mysql-bronze:
    image: mysql:8.0
    container_name: mysql-bronze
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./sql/mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  # Gold Layer: PostgreSQL
  postgres-gold:
    image: postgres:15
    container_name: postgres-gold
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/postgres-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  aviation-data-pipe:
    build: .
    depends_on:
      - mysql-bronze
    environment:
      - BRONZE_DB_HOST=${BRONZE_DB_HOST}
      - BRONZE_DB_USER=${BRONZE_DB_USER}
      - BRONZE_DB_PASSWORD=${BRONZE_DB_PASSWORD}

volumes:
  mysql-data:
  postgres-data:


