spring:
  datasource:
    url: jdbc:mysql://mysql-source:3306/aviation_transactional
    username: aviation_user
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
