opensky.api.url=https://opensky-network.org/api/states/all

# Bronze Layer Settings (MySQL)
bronze.db.port=3306
bronze.db.name=bronze_db

# Gold Layer Settings (PostgreSQL)
gold.db.port=5432
gold.db.name=gold_db


